/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedKartuRouteImport } from './routes/_authenticated/kartu'
import { Route as AuthenticatedTimRouteRouteImport } from './routes/_authenticated/tim/route'
import { Route as AuthenticatedWargaRouteRouteImport } from './routes/_authenticated/warga/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAduanRouteImport } from './routes/_authenticated/admin/aduan'
import { Route as AuthenticatedAdminHargaRouteImport } from './routes/_authenticated/admin/harga'
import { Route as AuthenticatedAdminJadwalRouteImport } from './routes/_authenticated/admin/jadwal'
import { Route as AuthenticatedAdminKasRouteImport } from './routes/_authenticated/admin/kas'
import { Route as AuthenticatedAdminLaporanRouteImport } from './routes/_authenticated/admin/laporan'
import { Route as AuthenticatedAdminNotifikasiRouteImport } from './routes/_authenticated/admin/notifikasi'
import { Route as AuthenticatedAdminPenggunaRouteImport } from './routes/_authenticated/admin/pengguna'
import { Route as AuthenticatedAdminPengumumanRouteImport } from './routes/_authenticated/admin/pengumuman'
import { Route as AuthenticatedAdminPickupRouteImport } from './routes/_authenticated/admin/pickup'
import { Route as AuthenticatedAdminProdukRouteImport } from './routes/_authenticated/admin/produk'
import { Route as AuthenticatedAdminTentangRouteImport } from './routes/_authenticated/admin/tentang'
import { Route as AuthenticatedAdminTransaksiRouteImport } from './routes/_authenticated/admin/transaksi'
import { Route as AuthenticatedTimIndexRouteImport } from './routes/_authenticated/tim/index'
import { Route as AuthenticatedTimPickupRouteImport } from './routes/_authenticated/tim/pickup'
import { Route as AuthenticatedTimProfilRouteImport } from './routes/_authenticated/tim/profil'
import { Route as AuthenticatedTimRekapRouteImport } from './routes/_authenticated/tim/rekap'
import { Route as AuthenticatedTimSetorRouteImport } from './routes/_authenticated/tim/setor'
import { Route as AuthenticatedWargaIndexRouteImport } from './routes/_authenticated/warga/index'
import { Route as AuthenticatedWargaAduanRouteImport } from './routes/_authenticated/warga/aduan'
import { Route as AuthenticatedWargaMarketplaceRouteImport } from './routes/_authenticated/warga/marketplace'
import { Route as AuthenticatedWargaProfilRouteImport } from './routes/_authenticated/warga/profil'
import { Route as AuthenticatedWargaTabunganRouteImport } from './routes/_authenticated/warga/tabungan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKartuRoute = AuthenticatedKartuRouteImport.update({
  id: '/kartu',
  path: '/kartu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimRouteRoute = AuthenticatedTimRouteRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWargaRouteRoute = AuthenticatedWargaRouteRouteImport.update({
  id: '/warga',
  path: '/warga',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAduanRoute = AuthenticatedAdminAduanRouteImport.update({
  id: '/aduan',
  path: '/aduan',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminHargaRoute = AuthenticatedAdminHargaRouteImport.update({
  id: '/harga',
  path: '/harga',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminJadwalRoute =
  AuthenticatedAdminJadwalRouteImport.update({
    id: '/jadwal',
    path: '/jadwal',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKasRoute = AuthenticatedAdminKasRouteImport.update({
  id: '/kas',
  path: '/kas',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminLaporanRoute =
  AuthenticatedAdminLaporanRouteImport.update({
    id: '/laporan',
    path: '/laporan',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotifikasiRoute =
  AuthenticatedAdminNotifikasiRouteImport.update({
    id: '/notifikasi',
    path: '/notifikasi',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPenggunaRoute =
  AuthenticatedAdminPenggunaRouteImport.update({
    id: '/pengguna',
    path: '/pengguna',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPengumumanRoute =
  AuthenticatedAdminPengumumanRouteImport.update({
    id: '/pengumuman',
    path: '/pengumuman',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPickupRoute =
  AuthenticatedAdminPickupRouteImport.update({
    id: '/pickup',
    path: '/pickup',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProdukRoute =
  AuthenticatedAdminProdukRouteImport.update({
    id: '/produk',
    path: '/produk',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTentangRoute =
  AuthenticatedAdminTentangRouteImport.update({
    id: '/tentang',
    path: '/tentang',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTransaksiRoute =
  AuthenticatedAdminTransaksiRouteImport.update({
    id: '/transaksi',
    path: '/transaksi',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedTimIndexRoute = AuthenticatedTimIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTimRouteRoute,
} as any)
const AuthenticatedTimPickupRoute = AuthenticatedTimPickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => AuthenticatedTimRouteRoute,
} as any)
const AuthenticatedTimProfilRoute = AuthenticatedTimProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedTimRouteRoute,
} as any)
const AuthenticatedTimRekapRoute = AuthenticatedTimRekapRouteImport.update({
  id: '/rekap',
  path: '/rekap',
  getParentRoute: () => AuthenticatedTimRouteRoute,
} as any)
const AuthenticatedTimSetorRoute = AuthenticatedTimSetorRouteImport.update({
  id: '/setor',
  path: '/setor',
  getParentRoute: () => AuthenticatedTimRouteRoute,
} as any)
const AuthenticatedWargaIndexRoute = AuthenticatedWargaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedWargaRouteRoute,
} as any)
const AuthenticatedWargaAduanRoute = AuthenticatedWargaAduanRouteImport.update({
  id: '/aduan',
  path: '/aduan',
  getParentRoute: () => AuthenticatedWargaRouteRoute,
} as any)
const AuthenticatedWargaMarketplaceRoute =
  AuthenticatedWargaMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedWargaRouteRoute,
  } as any)
const AuthenticatedWargaProfilRoute =
  AuthenticatedWargaProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedWargaRouteRoute,
  } as any)
const AuthenticatedWargaTabunganRoute =
  AuthenticatedWargaTabunganRouteImport.update({
    id: '/tabungan',
    path: '/tabungan',
    getParentRoute: () => AuthenticatedWargaRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/tim': typeof AuthenticatedTimRouteRouteWithChildren
  '/warga': typeof AuthenticatedWargaRouteRouteWithChildren
  '/kartu': typeof AuthenticatedKartuRoute
  '/admin/aduan': typeof AuthenticatedAdminAduanRoute
  '/admin/harga': typeof AuthenticatedAdminHargaRoute
  '/admin/jadwal': typeof AuthenticatedAdminJadwalRoute
  '/admin/kas': typeof AuthenticatedAdminKasRoute
  '/admin/laporan': typeof AuthenticatedAdminLaporanRoute
  '/admin/notifikasi': typeof AuthenticatedAdminNotifikasiRoute
  '/admin/pengguna': typeof AuthenticatedAdminPenggunaRoute
  '/admin/pengumuman': typeof AuthenticatedAdminPengumumanRoute
  '/admin/pickup': typeof AuthenticatedAdminPickupRoute
  '/admin/produk': typeof AuthenticatedAdminProdukRoute
  '/admin/tentang': typeof AuthenticatedAdminTentangRoute
  '/admin/transaksi': typeof AuthenticatedAdminTransaksiRoute
  '/tim/pickup': typeof AuthenticatedTimPickupRoute
  '/tim/profil': typeof AuthenticatedTimProfilRoute
  '/tim/rekap': typeof AuthenticatedTimRekapRoute
  '/tim/setor': typeof AuthenticatedTimSetorRoute
  '/warga/aduan': typeof AuthenticatedWargaAduanRoute
  '/warga/marketplace': typeof AuthenticatedWargaMarketplaceRoute
  '/warga/profil': typeof AuthenticatedWargaProfilRoute
  '/warga/tabungan': typeof AuthenticatedWargaTabunganRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/tim/': typeof AuthenticatedTimIndexRoute
  '/warga/': typeof AuthenticatedWargaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kartu': typeof AuthenticatedKartuRoute
  '/admin/aduan': typeof AuthenticatedAdminAduanRoute
  '/admin/harga': typeof AuthenticatedAdminHargaRoute
  '/admin/jadwal': typeof AuthenticatedAdminJadwalRoute
  '/admin/kas': typeof AuthenticatedAdminKasRoute
  '/admin/laporan': typeof AuthenticatedAdminLaporanRoute
  '/admin/notifikasi': typeof AuthenticatedAdminNotifikasiRoute
  '/admin/pengguna': typeof AuthenticatedAdminPenggunaRoute
  '/admin/pengumuman': typeof AuthenticatedAdminPengumumanRoute
  '/admin/pickup': typeof AuthenticatedAdminPickupRoute
  '/admin/produk': typeof AuthenticatedAdminProdukRoute
  '/admin/tentang': typeof AuthenticatedAdminTentangRoute
  '/admin/transaksi': typeof AuthenticatedAdminTransaksiRoute
  '/tim/pickup': typeof AuthenticatedTimPickupRoute
  '/tim/profil': typeof AuthenticatedTimProfilRoute
  '/tim/rekap': typeof AuthenticatedTimRekapRoute
  '/tim/setor': typeof AuthenticatedTimSetorRoute
  '/warga/aduan': typeof AuthenticatedWargaAduanRoute
  '/warga/marketplace': typeof AuthenticatedWargaMarketplaceRoute
  '/warga/profil': typeof AuthenticatedWargaProfilRoute
  '/warga/tabungan': typeof AuthenticatedWargaTabunganRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/tim': typeof AuthenticatedTimIndexRoute
  '/warga': typeof AuthenticatedWargaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/tim': typeof AuthenticatedTimRouteRouteWithChildren
  '/_authenticated/warga': typeof AuthenticatedWargaRouteRouteWithChildren
  '/_authenticated/kartu': typeof AuthenticatedKartuRoute
  '/_authenticated/admin/aduan': typeof AuthenticatedAdminAduanRoute
  '/_authenticated/admin/harga': typeof AuthenticatedAdminHargaRoute
  '/_authenticated/admin/jadwal': typeof AuthenticatedAdminJadwalRoute
  '/_authenticated/admin/kas': typeof AuthenticatedAdminKasRoute
  '/_authenticated/admin/laporan': typeof AuthenticatedAdminLaporanRoute
  '/_authenticated/admin/notifikasi': typeof AuthenticatedAdminNotifikasiRoute
  '/_authenticated/admin/pengguna': typeof AuthenticatedAdminPenggunaRoute
  '/_authenticated/admin/pengumuman': typeof AuthenticatedAdminPengumumanRoute
  '/_authenticated/admin/pickup': typeof AuthenticatedAdminPickupRoute
  '/_authenticated/admin/produk': typeof AuthenticatedAdminProdukRoute
  '/_authenticated/admin/tentang': typeof AuthenticatedAdminTentangRoute
  '/_authenticated/admin/transaksi': typeof AuthenticatedAdminTransaksiRoute
  '/_authenticated/tim/pickup': typeof AuthenticatedTimPickupRoute
  '/_authenticated/tim/profil': typeof AuthenticatedTimProfilRoute
  '/_authenticated/tim/rekap': typeof AuthenticatedTimRekapRoute
  '/_authenticated/tim/setor': typeof AuthenticatedTimSetorRoute
  '/_authenticated/warga/aduan': typeof AuthenticatedWargaAduanRoute
  '/_authenticated/warga/marketplace': typeof AuthenticatedWargaMarketplaceRoute
  '/_authenticated/warga/profil': typeof AuthenticatedWargaProfilRoute
  '/_authenticated/warga/tabungan': typeof AuthenticatedWargaTabunganRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/tim/': typeof AuthenticatedTimIndexRoute
  '/_authenticated/warga/': typeof AuthenticatedWargaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/tim'
    | '/warga'
    | '/kartu'
    | '/admin/aduan'
    | '/admin/harga'
    | '/admin/jadwal'
    | '/admin/kas'
    | '/admin/laporan'
    | '/admin/notifikasi'
    | '/admin/pengguna'
    | '/admin/pengumuman'
    | '/admin/pickup'
    | '/admin/produk'
    | '/admin/tentang'
    | '/admin/transaksi'
    | '/tim/pickup'
    | '/tim/profil'
    | '/tim/rekap'
    | '/tim/setor'
    | '/warga/aduan'
    | '/warga/marketplace'
    | '/warga/profil'
    | '/warga/tabungan'
    | '/admin/'
    | '/tim/'
    | '/warga/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kartu'
    | '/admin/aduan'
    | '/admin/harga'
    | '/admin/jadwal'
    | '/admin/kas'
    | '/admin/laporan'
    | '/admin/notifikasi'
    | '/admin/pengguna'
    | '/admin/pengumuman'
    | '/admin/pickup'
    | '/admin/produk'
    | '/admin/tentang'
    | '/admin/transaksi'
    | '/tim/pickup'
    | '/tim/profil'
    | '/tim/rekap'
    | '/tim/setor'
    | '/warga/aduan'
    | '/warga/marketplace'
    | '/warga/profil'
    | '/warga/tabungan'
    | '/admin'
    | '/tim'
    | '/warga'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/tim'
    | '/_authenticated/warga'
    | '/_authenticated/kartu'
    | '/_authenticated/admin/aduan'
    | '/_authenticated/admin/harga'
    | '/_authenticated/admin/jadwal'
    | '/_authenticated/admin/kas'
    | '/_authenticated/admin/laporan'
    | '/_authenticated/admin/notifikasi'
    | '/_authenticated/admin/pengguna'
    | '/_authenticated/admin/pengumuman'
    | '/_authenticated/admin/pickup'
    | '/_authenticated/admin/produk'
    | '/_authenticated/admin/tentang'
    | '/_authenticated/admin/transaksi'
    | '/_authenticated/tim/pickup'
    | '/_authenticated/tim/profil'
    | '/_authenticated/tim/rekap'
    | '/_authenticated/tim/setor'
    | '/_authenticated/warga/aduan'
    | '/_authenticated/warga/marketplace'
    | '/_authenticated/warga/profil'
    | '/_authenticated/warga/tabungan'
    | '/_authenticated/admin/'
    | '/_authenticated/tim/'
    | '/_authenticated/warga/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kartu': {
      id: '/_authenticated/kartu'
      path: '/kartu'
      fullPath: '/kartu'
      preLoaderRoute: typeof AuthenticatedKartuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tim': {
      id: '/_authenticated/tim'
      path: '/tim'
      fullPath: '/tim'
      preLoaderRoute: typeof AuthenticatedTimRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warga': {
      id: '/_authenticated/warga'
      path: '/warga'
      fullPath: '/warga'
      preLoaderRoute: typeof AuthenticatedWargaRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/aduan': {
      id: '/_authenticated/admin/aduan'
      path: '/aduan'
      fullPath: '/admin/aduan'
      preLoaderRoute: typeof AuthenticatedAdminAduanRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/harga': {
      id: '/_authenticated/admin/harga'
      path: '/harga'
      fullPath: '/admin/harga'
      preLoaderRoute: typeof AuthenticatedAdminHargaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/jadwal': {
      id: '/_authenticated/admin/jadwal'
      path: '/jadwal'
      fullPath: '/admin/jadwal'
      preLoaderRoute: typeof AuthenticatedAdminJadwalRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kas': {
      id: '/_authenticated/admin/kas'
      path: '/kas'
      fullPath: '/admin/kas'
      preLoaderRoute: typeof AuthenticatedAdminKasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/laporan': {
      id: '/_authenticated/admin/laporan'
      path: '/laporan'
      fullPath: '/admin/laporan'
      preLoaderRoute: typeof AuthenticatedAdminLaporanRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifikasi': {
      id: '/_authenticated/admin/notifikasi'
      path: '/notifikasi'
      fullPath: '/admin/notifikasi'
      preLoaderRoute: typeof AuthenticatedAdminNotifikasiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pengguna': {
      id: '/_authenticated/admin/pengguna'
      path: '/pengguna'
      fullPath: '/admin/pengguna'
      preLoaderRoute: typeof AuthenticatedAdminPenggunaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pengumuman': {
      id: '/_authenticated/admin/pengumuman'
      path: '/pengumuman'
      fullPath: '/admin/pengumuman'
      preLoaderRoute: typeof AuthenticatedAdminPengumumanRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pickup': {
      id: '/_authenticated/admin/pickup'
      path: '/pickup'
      fullPath: '/admin/pickup'
      preLoaderRoute: typeof AuthenticatedAdminPickupRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produk': {
      id: '/_authenticated/admin/produk'
      path: '/produk'
      fullPath: '/admin/produk'
      preLoaderRoute: typeof AuthenticatedAdminProdukRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tentang': {
      id: '/_authenticated/admin/tentang'
      path: '/tentang'
      fullPath: '/admin/tentang'
      preLoaderRoute: typeof AuthenticatedAdminTentangRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/transaksi': {
      id: '/_authenticated/admin/transaksi'
      path: '/transaksi'
      fullPath: '/admin/transaksi'
      preLoaderRoute: typeof AuthenticatedAdminTransaksiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/tim/': {
      id: '/_authenticated/tim/'
      path: '/'
      fullPath: '/tim/'
      preLoaderRoute: typeof AuthenticatedTimIndexRouteImport
      parentRoute: typeof AuthenticatedTimRouteRoute
    }
    '/_authenticated/tim/pickup': {
      id: '/_authenticated/tim/pickup'
      path: '/pickup'
      fullPath: '/tim/pickup'
      preLoaderRoute: typeof AuthenticatedTimPickupRouteImport
      parentRoute: typeof AuthenticatedTimRouteRoute
    }
    '/_authenticated/tim/profil': {
      id: '/_authenticated/tim/profil'
      path: '/profil'
      fullPath: '/tim/profil'
      preLoaderRoute: typeof AuthenticatedTimProfilRouteImport
      parentRoute: typeof AuthenticatedTimRouteRoute
    }
    '/_authenticated/tim/rekap': {
      id: '/_authenticated/tim/rekap'
      path: '/rekap'
      fullPath: '/tim/rekap'
      preLoaderRoute: typeof AuthenticatedTimRekapRouteImport
      parentRoute: typeof AuthenticatedTimRouteRoute
    }
    '/_authenticated/tim/setor': {
      id: '/_authenticated/tim/setor'
      path: '/setor'
      fullPath: '/tim/setor'
      preLoaderRoute: typeof AuthenticatedTimSetorRouteImport
      parentRoute: typeof AuthenticatedTimRouteRoute
    }
    '/_authenticated/warga/': {
      id: '/_authenticated/warga/'
      path: '/'
      fullPath: '/warga/'
      preLoaderRoute: typeof AuthenticatedWargaIndexRouteImport
      parentRoute: typeof AuthenticatedWargaRouteRoute
    }
    '/_authenticated/warga/aduan': {
      id: '/_authenticated/warga/aduan'
      path: '/aduan'
      fullPath: '/warga/aduan'
      preLoaderRoute: typeof AuthenticatedWargaAduanRouteImport
      parentRoute: typeof AuthenticatedWargaRouteRoute
    }
    '/_authenticated/warga/marketplace': {
      id: '/_authenticated/warga/marketplace'
      path: '/marketplace'
      fullPath: '/warga/marketplace'
      preLoaderRoute: typeof AuthenticatedWargaMarketplaceRouteImport
      parentRoute: typeof AuthenticatedWargaRouteRoute
    }
    '/_authenticated/warga/profil': {
      id: '/_authenticated/warga/profil'
      path: '/profil'
      fullPath: '/warga/profil'
      preLoaderRoute: typeof AuthenticatedWargaProfilRouteImport
      parentRoute: typeof AuthenticatedWargaRouteRoute
    }
    '/_authenticated/warga/tabungan': {
      id: '/_authenticated/warga/tabungan'
      path: '/tabungan'
      fullPath: '/warga/tabungan'
      preLoaderRoute: typeof AuthenticatedWargaTabunganRouteImport
      parentRoute: typeof AuthenticatedWargaRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAduanRoute: typeof AuthenticatedAdminAduanRoute
  AuthenticatedAdminHargaRoute: typeof AuthenticatedAdminHargaRoute
  AuthenticatedAdminJadwalRoute: typeof AuthenticatedAdminJadwalRoute
  AuthenticatedAdminKasRoute: typeof AuthenticatedAdminKasRoute
  AuthenticatedAdminLaporanRoute: typeof AuthenticatedAdminLaporanRoute
  AuthenticatedAdminNotifikasiRoute: typeof AuthenticatedAdminNotifikasiRoute
  AuthenticatedAdminPenggunaRoute: typeof AuthenticatedAdminPenggunaRoute
  AuthenticatedAdminPengumumanRoute: typeof AuthenticatedAdminPengumumanRoute
  AuthenticatedAdminPickupRoute: typeof AuthenticatedAdminPickupRoute
  AuthenticatedAdminProdukRoute: typeof AuthenticatedAdminProdukRoute
  AuthenticatedAdminTentangRoute: typeof AuthenticatedAdminTentangRoute
  AuthenticatedAdminTransaksiRoute: typeof AuthenticatedAdminTransaksiRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAduanRoute: AuthenticatedAdminAduanRoute,
    AuthenticatedAdminHargaRoute: AuthenticatedAdminHargaRoute,
    AuthenticatedAdminJadwalRoute: AuthenticatedAdminJadwalRoute,
    AuthenticatedAdminKasRoute: AuthenticatedAdminKasRoute,
    AuthenticatedAdminLaporanRoute: AuthenticatedAdminLaporanRoute,
    AuthenticatedAdminNotifikasiRoute: AuthenticatedAdminNotifikasiRoute,
    AuthenticatedAdminPenggunaRoute: AuthenticatedAdminPenggunaRoute,
    AuthenticatedAdminPengumumanRoute: AuthenticatedAdminPengumumanRoute,
    AuthenticatedAdminPickupRoute: AuthenticatedAdminPickupRoute,
    AuthenticatedAdminProdukRoute: AuthenticatedAdminProdukRoute,
    AuthenticatedAdminTentangRoute: AuthenticatedAdminTentangRoute,
    AuthenticatedAdminTransaksiRoute: AuthenticatedAdminTransaksiRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedTimRouteRouteChildren {
  AuthenticatedTimPickupRoute: typeof AuthenticatedTimPickupRoute
  AuthenticatedTimProfilRoute: typeof AuthenticatedTimProfilRoute
  AuthenticatedTimRekapRoute: typeof AuthenticatedTimRekapRoute
  AuthenticatedTimSetorRoute: typeof AuthenticatedTimSetorRoute
  AuthenticatedTimIndexRoute: typeof AuthenticatedTimIndexRoute
}

const AuthenticatedTimRouteRouteChildren: AuthenticatedTimRouteRouteChildren = {
  AuthenticatedTimPickupRoute: AuthenticatedTimPickupRoute,
  AuthenticatedTimProfilRoute: AuthenticatedTimProfilRoute,
  AuthenticatedTimRekapRoute: AuthenticatedTimRekapRoute,
  AuthenticatedTimSetorRoute: AuthenticatedTimSetorRoute,
  AuthenticatedTimIndexRoute: AuthenticatedTimIndexRoute,
}

const AuthenticatedTimRouteRouteWithChildren =
  AuthenticatedTimRouteRoute._addFileChildren(
    AuthenticatedTimRouteRouteChildren,
  )

interface AuthenticatedWargaRouteRouteChildren {
  AuthenticatedWargaAduanRoute: typeof AuthenticatedWargaAduanRoute
  AuthenticatedWargaMarketplaceRoute: typeof AuthenticatedWargaMarketplaceRoute
  AuthenticatedWargaProfilRoute: typeof AuthenticatedWargaProfilRoute
  AuthenticatedWargaTabunganRoute: typeof AuthenticatedWargaTabunganRoute
  AuthenticatedWargaIndexRoute: typeof AuthenticatedWargaIndexRoute
}

const AuthenticatedWargaRouteRouteChildren: AuthenticatedWargaRouteRouteChildren =
  {
    AuthenticatedWargaAduanRoute: AuthenticatedWargaAduanRoute,
    AuthenticatedWargaMarketplaceRoute: AuthenticatedWargaMarketplaceRoute,
    AuthenticatedWargaProfilRoute: AuthenticatedWargaProfilRoute,
    AuthenticatedWargaTabunganRoute: AuthenticatedWargaTabunganRoute,
    AuthenticatedWargaIndexRoute: AuthenticatedWargaIndexRoute,
  }

const AuthenticatedWargaRouteRouteWithChildren =
  AuthenticatedWargaRouteRoute._addFileChildren(
    AuthenticatedWargaRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedTimRouteRoute: typeof AuthenticatedTimRouteRouteWithChildren
  AuthenticatedWargaRouteRoute: typeof AuthenticatedWargaRouteRouteWithChildren
  AuthenticatedKartuRoute: typeof AuthenticatedKartuRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedTimRouteRoute: AuthenticatedTimRouteRouteWithChildren,
  AuthenticatedWargaRouteRoute: AuthenticatedWargaRouteRouteWithChildren,
  AuthenticatedKartuRoute: AuthenticatedKartuRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
